config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  resources :users, only: [:show, :edit, :update]
  resources :movies, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  root :to => 'homes#top'
  get 'homes/about'
  get 'search' => 'movies#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  
  validates :body, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :comments, dependent: :destroy
  attachment :image
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    when 'likes'
      return find(Like.group(:movie_id).order('count(movie_id) desc').pluck(:movie_id))
    when 'comment'
      return find(Comment.group(:movie_id).order('count(movie_id) desc').pluck(:movie_id))
    end
  end

  def favorited_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @movie = Movie.find(params[:movie_id])
    @comment = current_user.comments.new(comment_params)
    @comment.movie_id = @movie.id
    if @comment.save
      redirect_to movie_path(@movie), notice: "コメント投稿しました"
    else
      @comments = @movie.comments
      @genre = @movie.genre
      render template: 'movies/show'
    end
  end

  def destroy
    Comment.find_by(id: params[:id], movie_id: params[:movie_id]).destroy
		redirect_to request.referer, notice: "コメント削除しました"
  end

  private
  def comment_params
    params.require(:comment).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
        @movies = Movie.all.reverse_order.limit(4)
        @all_ranks = Movie.find(Like.group(:movie_id).order('count(movie_id) desc').limit(4).pluck(:movie_id))
        @genres = Genre.all
    end

    def about
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    movie = Movie.find(params[:movie_id])
    like = current_user.likes.new(movie_id: movie.id)
    like.save
    redirect_to movie_path(movie)
  end

  def destroy
    movie = Movie.find(params[:movie_id])
    like = current_user.likes.find_by(movie_id: movie.id)
    like.destroy
    redirect_to movie_path(movie)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
    @genres = Genre.all
    if params[:genre_id].present?
      @movies = Movie.where(genre_id: params[:genre_id]).page(params[:page]).per(5).reverse_order
    else
      @movies = Movie.page(params[:page]).per(5).reverse_order
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @genre = @movie.genre
    @comments = @movie.comments
    @comment = Comment.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "新規投稿しました"
    else
      @user = current_user
      @movies = @user.movies.page(params[:page]).per(4).reverse_order
      @comment = @user.comments.page(params[:page]).per(4).reverse_order
      render template: "users/show"
    end
  end

  def edit
    @movie = Movie.find(params[:id])
		if @movie.user != current_user
			redirect_to movies_path
		end
  end

  def update
    @movie = Movie.find(params[:id])
		@movie.update(movie_params)
		if @movie.save
			redirect_to movie_path(@movie.id), notice: "編集しました"
		else
			render "edit"
		end
  end

  def destroy
    @movie = Movie.find(params[:id])
		@movie.destroy
		redirect_to request.referer, notice: "削除しました"
  end

  def search
    @genres = Genre.all
    selection = params[:keyword]
    case selection
    when 'new'
      @movies = Movie.page(params[:page]).order(created_at: :DESC).per(5)
    when 'old'
      @movies = Movie.page(params[:page]).order(created_at: :ASC).per(5)
    when 'likes'
      @movies = Movie.page(params[:page]).left_joins(:likes).group(:id).order(Arel.sql('COUNT(likes.id) DESC')).per(5)
    when 'comment'
      @movies = Movie.page(params[:page]).left_joins(:comments).group(:id).order(Arel.sql('count(comments.id) DESC')).per(5)
    end
  end

  private
  def movie_params
    params[:movie][:user_id] = current_user.id
    params.require(:movie).permit(:title, :body, :user_id, :genre_id, :image)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @movie = Movie.new
    @movies = @user.movies.page(params[:page]).per(4).reverse_order
    @comment = @user.comments.page(params[:page]).per(4).reverse_order
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div class=“alert alert-warning”>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="row">
          <nav class="navbar-nav navbar-left">
            <p class="text-light">Movies</p>
          </nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li>
              <%= link_to "トップ", root_path %>
            </li>
            <li>
              <%= link_to homes_about_path do %>
              <p><span class="glyphicon glyphicon-link" aria-hidden="true"></span> アバウト</p>
              <% end %>
            </li>
            <li>
              <%= link_to user_path(current_user) do %>
              <p><span class="glyphicon glyphicon-home" aria-hidden="true"></span>マイページ</p>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <p><span class="glyphicon glyphicon-log-out logout" aria-hidden="true"></span> ログアウト</p>
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to root_path do %>
              <p><span class="glyphicon glyphicon-home" aria-hidden="true"></span> トップ</p>
              <% end %>
            </li>
            <li>
              <%= link_to homes_about_path do %>
              <p><span class="glyphicon glyphicon-link" aria-hidden="true"></span> アバウト</p>
              <% end %>
            </li>
            <li>
              <%=link_to new_user_registration_path do %>
              <p><span class="glyphicon glyphicon-edit sign_up" aria-hidden="true"></span> サインアップ</p>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
              <p><span class="glyphicon glyphicon-log-in sign_in" aria-hidden="true"> ログイン</span></p>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <p id=“notice”><%= notice %></p>
    <%= yield %>
  </body>
</html>